### ISSUE TITLE
Doesn't seem to work with SublimeText3

### ISSUE THREAD

**Issue by hamishmcn** [lengstrom/MathEvaluator#10]
Installed using Package Control with SublimeText 3, Stable Channel 3083 (on Windows 8.1)
Ctrl-Shift-M didn't seem to do anything.
I enabled debug logging in Package Control, restarted ST and looked at the console.
When loading it complained about a 'print' statement in "Selection Evaluator.mathevaluator". 
I opened the .py file and replaced the 'print' a Python3 style print statement and now there are no errors, but Ctrl-Shift-M still doesn't do anything

**Comment by lengstrom** [comment]
fixed, sorry, accidentally switched around `dev` and `master` branches
