### ISSUE TITLE
Missing in PackageControl

### ISSUE THREAD

**Issue by srbs** [lengstrom/MathEvaluator#9]
Since you've moved to [/lengstrom](https://github.com/lengstrom) from [/meadowstream](https://github.com/meadowstream), the [Selection Evaluator](https://packagecontrol.io/packages/Selection%20Evaluator) plugin is no longer available because it is 'missing'.

**Comment by lengstrom** [comment]
Thanks - how can I fix this?

**Comment by srbs** [comment]
1. Fork the [package_control_channel](https://github.com/wbond/package_control_channel) repository
2. Update the `details` value in the [/repository/s.json](https://github.com/wbond/package_control_channel/blob/master/repository/s.json) file (currently [line 644](https://github.com/wbond/package_control_channel/blob/master/repository/s.json#L644))
3. Submit a pull request

Similar to steps 2, 3c, 4, 5 from [this doc](https://packagecontrol.io/docs/renaming_a_package).

**Comment by lengstrom** [comment]
Thanks for the help, did it!

**Comment by srbs** [comment]
Awesome, thanks a lot!
